name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.0', '2.7', '2.6', '2.5', '2.4']
        frozen_string_literal: ['yes', 'no']
        exclude:
          - ruby: '2.5'
            frozen_string_literal: 'yes'
          - ruby: '2.4'
            frozen_string_literal: 'yes'

    env:
      RGGEN_ROOT: ${{ github.workspace }}
      RUBYOPT: ${{ (matrix.frozen_string_literal == 'yes' && '--enable-frozen-string-literal') || '' }}
      USE_FIXED_GEMS: ${{ matrix.frozen_string_literal }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout RgGen library list
        uses: actions/checkout@v2
        with:
          repository: rggen/rggen-checkout
          path: rggen-checkout
          fetch-depth: 0

      - name: Checkout RgGen libraries
        run: |
          ${RGGEN_ROOT}/rggen-checkout/bin/checkout.sh

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle exec rake coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          name: ${{ runner.os }}-${{ matrix.ruby }}-frozen_string_literal-${{ matrix.frozen_string_literal }}
          file: ./coverage/coverage.xml
          fail_ci_if_error: true
